### ISSUE TITLE
No sql file

### ISSUE THREAD

**Issue by danny007in** [hemant6488/StudentManagementSystem#2]

**Comment by OsamaHussain** [comment]
download database from here

https://github.com/thasneemilm/CodeIgniterESMS092015/blob/master/codeigniter3tests%20(1).sql

**Comment by danny007in** [comment]
> 
> 
> download database from here
> 
> https://github.com/thasneemilm/CodeIgniterESMS092015/blob/master/codeigniter3tests%20(1).sql

Better to create PR for this

**Comment by OsamaHussain** [comment]
PR means

**Comment by danny007in** [comment]
> 
> 
> PR means

Pull request
